meta:
  url: https://pirosikick.github.io/integration-test-is-awesome/
  title: Integration Test、いいぞ
  description: FukuokaJS第14回の登壇資料です。Testing TrophyのIntegration Testがいいぞという話です。
  siteName:
  sns: ["twitter"]
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
build:
  publicPath: "/integration-test-is-awesome/"
